<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category    Esites
 * @package     Esites_Editor
 * @copyright   Copyright (c) 2015 E-sites (http://www.e-sites.nl)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<script src="/js/esites_editor/dist/js/vendor/requirejs/require.js"></script>
<script>
	(function (window) {
		var doc = window.document,
			esites_editor = {
				instances: [],
				version: '<?php echo $this->getExtensionVersion(); ?>',
				settings: <?php echo json_encode($this->getEditorConfig()); ?>,
				init: function () {
					requirejs(['/js/esites_editor/dist/js/app.js']);
				}
			};

		if ( 'addEventListener' in window ) {
			doc.addEventListener('DOMContentLoaded', esites_editor.init);
		} else {
			window.onload = esites_editor.init;
		}

		window.esites_editor = esites_editor;
	}(this));
</script>